AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nutri-track-bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  handleRequest:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: nutri-track-bot
      Handler: com.nutritrack.bot.LambdaHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          CCH_PASS: postgres
          CCH_URL: jdbc:postgresql://172.17.0.2/cch_helper
          CCH_USER: postgres
          BOT_TOKEN: 7174218865:AAFOWA-mG-_Tt0_oiuRO04CAWiH3OwEef54
          BOT_NAME: PipiSosiska
      Events:
        CountCaloryHelper:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cch
            Method: post
