package com.nutritrack.bot.repository;

public enum SqlQuery {
    SAVE_USER,
    UPDATE_USER,
    GET_USER,
    SAVE_FOOD,
    UPDATE_FOOD,
    GET_COOKING_FOOD,
    GET_CALCULATION_FOOD,
    GET_FOOD_BY_ID_AND_NAME,
    DELETE_PROCESSED_FOOD,
    GET_USER_COOKED_FOOD,
    GET_FOOD_BY_ID,
    GET_PROCESSED_FOOD_BY_USER_ID,
    GET_ALL_USERS_FOOD,
    DELETE_FOOD_BY_ID,
    DELETE_USER_FOOD
}
